Improve handling of reference repos
Change-Id: If195d5c2367fe286118454ff0ccf7c4c5ebc383f

diff --git a/make-source-package b/make-source-package
--- a/make-source-package
+++ b/make-source-package
@@ -49,10 +49,11 @@ then
 		REFREPO=$REFREPODIR/$PROJ
 		if [ -d "$REFREPO.git" ]; then
 			REF=--reference=$REFREPO.git
-		elif [ -d "$REFREPO" ]; then
-			REF=--reference=$REFREPO
+		elif [ -d "$REFREPO/.git" ]; then
+			REF=--reference=$REFREPO/.git
 		else
-			REF=
+			echo "Can't reference $REFREPO.git or $REFREPO/.git" >&2
+			exit 1
 		fi
 	fi
 
